//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string Role { get; set; }
    
        public virtual EmployeeInfoStore EmployeeInfoStore { get; set; }
    }
}
